services:
  - type: web
    name: lumina-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_SSL
        value: "true"
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ORIGENS_PERMITIDAS
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: APPYPAY_API_URL
        sync: false
      - key: APPYPAY_API_KEY
        sync: false
      - key: APPYPAY_WEBHOOK_SECRET
        sync: false
      - key: CJ_API_KEY
        sync: false
      - key: CJ_LOGISTIC_NAME
        sync: false
      - key: BUCKYDROP_API_URL
        sync: false
      - key: BUCKYDROP_APPCODE
        sync: false
      - key: BUCKYDROP_APPSECRET
        sync: false
      - key: EXCHANGE_RATE_API_URL
        sync: false
      - key: EXCHANGE_RATE_API_KEY
        sync: false
      - key: EXCHANGE_RATE_USD_EUR_URL
        value: https://api.frankfurter.app/latest?from=USD&to=EUR
      - key: AGENTE_NOME
        sync: false
      - key: AGENTE_LINHA1
        sync: false
      - key: AGENTE_CIDADE
        sync: false
      - key: AGENTE_CODIGO_POSTAL
        sync: false
      - key: AGENTE_PAIS
        sync: false
      - key: AGENTE_TELEFONE
        sync: false
