-- LÚMINA — campos comerciais/SEO para personalização de produtos
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS descricao_curta TEXT;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS preco_compare_eur NUMERIC(10,2) NOT NULL DEFAULT 0;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS seo_title VARCHAR(180);
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS seo_description VARCHAR(320);
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS video_url TEXT;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS beneficios TEXT;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS ingredientes TEXT;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS modo_uso TEXT;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS tipo_pele VARCHAR(180);
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS tipo_cabelo VARCHAR(180);
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS etiqueta VARCHAR(60);
