const express=require('express');const {transaction,query}=require('../config/db');const {travarCambioParaPedido}=require('../integrations/cambio');const {resolverMoradaParaFornecedor}=require('../integrations/roteamento-envio');const {criarSessaoStripe}=require('../integrations/pagamentos-eur');const {criarCobranca}=require('../integrations/appypay');
const router=express.Router();
router.post('/',async(req,res,next)=>{try{const {itens,moradaEntrega,moeda,telefoneCliente,clienteId,email,nome}=req.body;if(!Array.isArray(itens)||!itens.length)return res.status(400).json({erro:'Carrinho vazio.'});if(!moradaEntrega?.pais||!moradaEntrega?.linha1||!moradaEntrega?.cidade)return res.status(400).json({erro:'Morada incompleta.'});if(!['EUR','AOA'].includes(moeda))return res.status(400).json({erro:'Moeda inválida.'});
 const ids=itens.map(i=>Number(i.produtoId));const r=await query(`SELECT p.*,c.nome categoria_nome FROM produtos p LEFT JOIN categorias c ON c.id=p.categoria_id WHERE p.id=ANY($1::bigint[]) AND p.ativo=true`,[ids]);if(r.rowCount!==new Set(ids).size)return res.status(400).json({erro:'Um ou mais produtos não estão disponíveis.'});const by=new Map(r.rows.map(p=>[Number(p.id),p]));let total=0;const resolvidos=[];for(const i of itens){const p=by.get(Number(i.produtoId));const q=Number(i.quantidade);if(!Number.isInteger(q)||q<1)return res.status(400).json({erro:'Quantidade inválida.'});if(Number(p.stock)<q)return res.status(409).json({erro:`Stock insuficiente para ${p.nome}.`});total+=Number(p.preco_venda_eur)*q;resolvidos.push({produtoId:Number(p.id),nomeProduto:p.nome,fornecedor:p.fornecedor,quantidade:q,preco:Number(p.preco_venda_eur),idFornecedor:p.id_fornecedor,skuFornecedor:p.sku_fornecedor});}
 const rota=resolverMoradaParaFornecedor(moradaEntrega.pais,{...moradaEntrega,nome,email,telefone:telefoneCliente});let cambio=null;if(moeda==='AOA'){if(!telefoneCliente)return res.status(400).json({erro:'Telefone obrigatório para pagamento em AOA.'});cambio=await travarCambioParaPedido(total)}
 const pedido=await transaction(async c=>{const pr=await c.query(`INSERT INTO pedidos(cliente_id,total_eur,moeda,cambio_taxa_usada,cambio_valor_eur,cambio_valor_aoa,cambio_data,entrega_linha1,entrega_linha2,entrega_cidade,entrega_codigo_postal,entrega_pais,entrega_telefone,rota_envio,fornecedor_morada_nome,fornecedor_morada_linha1,fornecedor_morada_cidade,fornecedor_morada_cp,fornecedor_morada_pais,fornecedor_morada_telefone,fornecedor_morada_ref,estado) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,'novo') RETURNING *`,[clienteId||null,total,moeda,cambio?.taxaUsada||null,cambio?.valorEUR||null,cambio?.valorAOA||null,cambio?.dataCambio||null,moradaEntrega.linha1,moradaEntrega.linha2||null,moradaEntrega.cidade,moradaEntrega.codigoPostal||null,moradaEntrega.pais,telefoneCliente||null,rota.tipo,rota.morada.nome,rota.morada.linha1,rota.morada.cidade,rota.morada.codigoPostal,rota.morada.pais,rota.morada.telefone,rota.morada.referenciaInterna||null]);const p=pr.rows[0];for(const i of resolvidos)await c.query(`INSERT INTO pedido_itens(pedido_id,produto_id,nome_produto,fornecedor,quantidade,preco_unitario_eur) VALUES($1,$2,$3,$4,$5,$6)`,[p.id,i.produtoId,i.nomeProduto,i.fornecedor,i.quantidade,i.preco]);return p});
 let pagamento;if(moeda==='EUR')pagamento=await criarSessaoStripe({pedidoId:pedido.numero,valorEUR:total,email});else pagamento=await criarCobranca({pedidoId:pedido.numero,valorAOA:cambio.valorAOA,telefoneCliente});
 await query(`INSERT INTO pedido_pagamentos(pedido_id,metodo,estado,id_cobranca,url_checkout) VALUES($1,$2,'pendente',$3,$4)`,[pedido.id,moeda==='EUR'?'stripe':'appypay',pagamento.idCobranca||null,pagamento.urlCheckout||null]);
 res.status(201).json({numeroPedido:pedido.numero,totalEUR:total,totalAOA:cambio?.valorAOA||null,rotaEnvio:rota.tipo,pagamento:{metodo:moeda==='EUR'?'stripe':'appypay',idCobranca:pagamento.idCobranca||null,urlCheckout:pagamento.urlCheckout||null,estado:'pendente'}});
}catch(e){next(e)}});module.exports=router;
