const express=require('express');const {query,transaction}=require('../config/db');const {exigirAutenticacao}=require('../middleware/auth');const router=express.Router();
function map(p,items,fs,pay){return{numeroPedido:p.numero,estado:p.estado,clienteId:p.cliente_id,totalEUR:Number(p.total_eur),moeda:p.moeda,rotaEnvio:p.rota_envio,moradaEntrega:{linha1:p.entrega_linha1,linha2:p.entrega_linha2,cidade:p.entrega_cidade,codigoPostal:p.entrega_codigo_postal,pais:p.entrega_pais,telefone:p.entrega_telefone},itens:items?.rows||[],fornecedores:fs?.rows||[],pagamento:pay?.rows?.[0]||null,criadoEm:p.criado_em}}
async function load(id){const p=(await query('SELECT * FROM pedidos WHERE id=$1 OR numero=$1 LIMIT 1',[id])).rows[0];if(!p)return null;const items=await query('SELECT * FROM pedido_itens WHERE pedido_id=$1 ORDER BY id',[p.id]);const fs=await query('SELECT * FROM pedido_fornecedores WHERE pedido_id=$1',[p.id]);const pay=await query('SELECT * FROM pedido_pagamentos WHERE pedido_id=$1',[p.id]);return map(p,items,fs,pay)}
router.get('/rastrear/:numeroPedido',async(req,res,next)=>{try{const p=await load(req.params.numeroPedido);if(!p)return res.status(404).json({erro:'Pedido não encontrado.'});res.json({numeroPedido:p.numeroPedido,estado:p.estado,rotaEnvio:p.rotaEnvio,fornecedores:p.fornecedores})}catch(e){next(e)}});
router.get('/meus',exigirAutenticacao('cliente'),async(req,res,next)=>{try{const r=await query('SELECT id FROM pedidos WHERE cliente_id=$1 ORDER BY criado_em DESC',[req.utilizador.id]);const out=[];for(const x of r.rows)out.push(await load(x.id));res.json(out)}catch(e){next(e)}});
router.get('/meus/:numeroPedido',exigirAutenticacao('cliente'),async(req,res,next)=>{try{const row=(await query('SELECT id FROM pedidos WHERE numero=$1 AND cliente_id=$2',[req.params.numeroPedido,req.utilizador.id])).rows[0];if(!row)return res.status(404).json({erro:'Pedido não encontrado.'});const p=await load(row.id);res.json(p)}catch(e){next(e)}});
router.get('/',exigirAutenticacao('admin'),async(req,res,next)=>{try{const r=await query('SELECT id FROM pedidos ORDER BY criado_em DESC');const out=[];for(const x of r.rows)out.push(await load(x.id));res.json(out)}catch(e){next(e)}});
router.get('/:numeroPedido',exigirAutenticacao('admin'),async(req,res,next)=>{try{const p=await load(req.params.numeroPedido);if(!p)return res.status(404).json({erro:'Pedido não encontrado.'});res.json(p)}catch(e){next(e)}});
router.put('/:numeroPedido/fornecedor/:fornecedor',exigirAutenticacao('admin'),async(req,res,next)=>{try{const p=(await query('SELECT id FROM pedidos WHERE numero=$1',[req.params.numeroPedido])).rows[0];if(!p)return res.status(404).json({erro:'Pedido não encontrado.'});const allowed=['rastreio1','rastreio2','estado','id_pedido_fornecedor','prazo_estimado_dias'];const sets=[],vals=[];for(const k of allowed)if(req.body[k]!==undefined){vals.push(req.body[k]);sets.push(`${k}=$${vals.length}`)}if(!sets.length)return res.status(400).json({erro:'Nenhuma alteração.'});vals.push(p.id,req.params.fornecedor);const r=await query(`UPDATE pedido_fornecedores SET ${sets.join(',')} WHERE pedido_id=$${vals.length-1} AND fornecedor=$${vals.length} RETURNING *`,vals);if(!r.rowCount)return res.status(404).json({erro:'Fornecedor não encontrado neste pedido.'});res.json(r.rows[0])}catch(e){next(e)}});
module.exports=router;
