const express=require('express');const crypto=require('crypto');const {query,transaction}=require('../config/db');const {client:stripeClient}=require('../integrations/pagamentos-eur');const cj=require('../integrations/cj-api');const bucky=require('../integrations/buckydrop-api');
const router=express.Router();
async function fulfill(numero){await transaction(async c=>{const p=(await c.query('SELECT * FROM pedidos WHERE numero=$1 FOR UPDATE',[numero])).rows[0];if(!p)return;if((await c.query("SELECT estado FROM pedido_pagamentos WHERE pedido_id=$1",[p.id])).rows[0]?.estado!=='pago')return;if(['processando','enviado_ao_agente','a_caminho','a_caminho_destino_final','entregue'].includes(p.estado))return;const items=(await c.query('SELECT * FROM pedido_itens WHERE pedido_id=$1 ORDER BY id',[p.id])).rows;for(const i of items){if(i.variante_id){const r=await c.query('UPDATE produto_variantes SET stock=stock-$1 WHERE id=$2 AND stock>=$1 RETURNING id',[i.quantidade,i.variante_id]);if(!r.rowCount)throw new Error(`Stock insuficiente na variante do produto ${i.nome_produto}.`);}else if(i.produto_id){const r=await c.query('UPDATE produtos SET stock=stock-$1 WHERE id=$2 AND stock>=$1 RETURNING id',[i.quantidade,i.produto_id]);if(!r.rowCount)throw new Error(`Stock insuficiente no produto ${i.nome_produto}.`);}}const grupos={};for(const i of items)(grupos[i.fornecedor]??=[]).push(i);const morada={nome:p.fornecedor_morada_nome,linha1:p.fornecedor_morada_linha1,cidade:p.fornecedor_morada_cidade,codigoPostal:p.fornecedor_morada_cp,pais:p.fornecedor_morada_pais,telefone:p.fornecedor_morada_telefone};for(const fornecedor of Object.keys(grupos)){
  // 'proprio' = stock próprio da Lúmina: não há API de fornecedor externo a acionar, o
  // pedido segue para expedição manual (a equipa embala e regista o rastreio no admin).
  if(fornecedor==='proprio')continue;
  const api=fornecedor==='cj'?cj:(fornecedor==='buckydrop'?bucky:null);
  if(!api)continue;
  try{
    const r=await api.criarPedido({pedidoId:p.numero,itens:grupos[fornecedor],moradaEntrega:morada,logisticName:p.metodo_envio});
    await c.query(`INSERT INTO pedido_fornecedores(pedido_id,fornecedor,id_pedido_fornecedor,prazo_estimado_dias,estado) VALUES($1,$2,$3,$4,'processando') ON CONFLICT(pedido_id,fornecedor) DO UPDATE SET id_pedido_fornecedor=EXCLUDED.id_pedido_fornecedor,prazo_estimado_dias=EXCLUDED.prazo_estimado_dias`,[p.id,fornecedor,r.idPedidoFornecedor,r.prazoEstimadoDias]);
  }catch(e){
    // Um fornecedor falhar (ex: API ainda não configurada) não pode travar o pedido inteiro —
    // fica registado para a equipa tratar manualmente a partir do admin.
    console.error(`[fulfill] Falha ao criar pedido no fornecedor ${fornecedor} para ${p.numero}:`,e.message);
  }
}await c.query("UPDATE pedidos SET estado='processando' WHERE id=$1",[p.id]);});}
router.post('/stripe',async(req,res)=>{try{if(!process.env.STRIPE_WEBHOOK_SECRET)return res.status(503).json({erro:'Stripe webhook não configurado.'});const sig=req.headers['stripe-signature'];let event;try{event=stripeClient().webhooks.constructEvent(req.body,sig,process.env.STRIPE_WEBHOOK_SECRET)}catch(e){return res.status(400).json({erro:'Assinatura Stripe inválida.'})}if(['checkout.session.completed','checkout.session.async_payment_succeeded'].includes(event.type)){const s=event.data.object;const numero=s.metadata?.pedidoId||s.client_reference_id;if(numero){const p=(await query('SELECT id FROM pedidos WHERE numero=$1',[numero])).rows[0];if(p){await query("UPDATE pedido_pagamentos SET estado='pago',id_cobranca_confirmada=$1 WHERE pedido_id=$2",[s.id,p.id]);await fulfill(numero)}}}res.json({received:true})}catch(e){console.error(e);res.status(500).json({erro:'Erro no webhook Stripe.'})}});
router.post('/appypay',async(req,res)=>{try{const expected=process.env.APPYPAY_WEBHOOK_SECRET;if(!expected||req.headers['x-appypay-webhook-secret']!==expected)return res.status(401).json({erro:'Webhook não autorizado.'});const d=req.body,numero=d.externalReference||d.numeroPedido||d.orderReference,id=d.id||d.reference||d.chargeId;if(!numero||!id)return res.status(400).json({erro:'Payload AppyPay incompleto.'});const p=(await query('SELECT id FROM pedidos WHERE numero=$1',[numero])).rows[0];if(!p)return res.status(404).json({erro:'Pedido não encontrado.'});const estado=String(d.status||'').toLowerCase();if(['paid','success','completed','confirmed'].includes(estado)){await query("UPDATE pedido_pagamentos SET estado='pago',id_cobranca_confirmada=$1 WHERE pedido_id=$2",[id,p.id]);await fulfill(numero)}res.json({received:true})}catch(e){console.error(e);res.status(500).json({erro:'Erro no webhook AppyPay.'})}});
router.post('/tracking/:fornecedor',async(req,res,next)=>{try{const fornecedor=req.params.fornecedor;if(!['cj','buckydrop'].includes(fornecedor))return res.status(400).json({erro:'Fornecedor inválido.'});const expected=fornecedor==='cj'?process.env.CJ_TRACKING_WEBHOOK_SECRET:process.env.BUCKYDROP_TRACKING_WEBHOOK_SECRET;const received=String(req.headers['x-lumina-webhook-secret']||'');if(!expected)return res.status(503).json({erro:'Webhook de tracking não configurado.'});const a=Buffer.from(received),b=Buffer.from(String(expected));if(a.length!==b.length||!require('crypto').timingSafeEqual(a,b))return res.status(401).json({erro:'Webhook não autorizado.'});const {numeroPedido,codigoRastreio,estado}=req.body;const p=(await query('SELECT id,rota_envio FROM pedidos WHERE numero=$1',[numeroPedido])).rows[0];if(!p)return res.status(404).json({erro:'Pedido não encontrado.'});await query('UPDATE pedido_fornecedores SET rastreio1=COALESCE($1,rastreio1),estado=COALESCE($2,estado) WHERE pedido_id=$3 AND fornecedor=$4',[codigoRastreio,estado,p.id,fornecedor]);await query("UPDATE pedidos SET estado=$1 WHERE id=$2",[p.rota_envio==='agente_de_carga'?'enviado_ao_agente':'a_caminho',p.id]);res.json({sucesso:true})}catch(e){next(e)}});
module.exports=router;
module.exports.fulfillPedido=fulfill;
